RUMM-1901 Add 'source' property in the common schema
DataDog/rum-events-format pull request #53
Opened 2022-01-11 14:45 UTC by mariusc83

As a follow up on the https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2290156382/RFC+-+Display+the+event+types+in+a+Hybrid+application RFC we are going to add a new `source` property in the `_common-schema.json`:
```
"source": {
      "type": "string",
      "description": "The source of this event",
      "enum": ["android", "ios", "browser", "flutter", "react-native", "cordova"],
      "readOnly": true
    }
```

2022-01-11 14:47 UTC, bcaudan commented on schemas/_common-schema.json
> +  "required": ["date", "application", "session", "view", "_dd", "source"],
cf [guideline](https://github.com/DataDog/rum-events-format#guidelines):
> New fields must not be set as required

2022-01-11 15:13 UTC, buranmert approved these changes

2022-01-11 15:20 UTC, bcaudan approved these changes

2022-01-12 12:05 UTC, xgouchet requested changes

2022-01-12 12:05 UTC, xgouchet commented on schemas/_common-schema.json
> +      "enum": ["android", "ios", "browser", "flutter", "react-native", "cordova"],
Do we already know what the `cordova`/ `ionic`/`phonegap` value should be? Let's only add the known ones for now and add any new one later when it's also supported by the backend

2022-01-12 13:03 UTC, louisj-dd approved these changes

2022-01-13 09:20 UTC, xgouchet approved these changes

2022-01-13 09:22 UTC, merged